### ISSUE TITLE
`tests/helpers/responsive.js` not generated

### ISSUE THREAD

**Issue by ngyv** [freshbooks/ember-responsive#127]
Not sure if the docs are outdated but adding `import './responsive';` in `start-app` results in error because `tests/helpers/responsive.js` is not generated.

**Comment by k-fish** [comment]
The docs should be updated for the v3 beta, but you don't need to import `responsive` in `start-app`. 

`import { setBreakpoint } from 'ember-responsive/test-support';` will work in acceptance and integration.

**Comment by pablogravielseo** [comment]
When I use `setBreakpointForIntegrationTest` from `import { setBreakpoint } from 'ember-responsive/test-support';`, I got the following error: 

```
TypeError: (0 , _testSupport.setBreakpointForIntegrationTest) is not a function
```

**Comment by Fabschu** [comment]
Im using ember-cli 2.16.2 and the integration test: 
`import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';
import { setBreakpoint } from 'ember-responsive/test-support';

moduleForComponent('wishlist-filter', 'Integration | Component | wishlist filter', {
  integration: true
});

test('it renders', function(assert) {
  setBreakpoint(this, 'large');
  // Set any properties with this.set('myProperty', 'value');
  // Handle any actions with this.on('myAction', function(val) { ... });
  this.render(hbs`{{wishlist-filter media=media}}`);

  assert.equal(this.$().text().trim(), '');
});`

fails with: 

> TypeError: Cannot read property 'lookup' of undefined
    at setBreakpoint (http://localhost:4200/assets/test-support.js:12746:29)
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:868:36)
    at runTest (http://localhost:4200/assets/test-support.js:4106:30)
    at Test.run (http://localhost:4200/assets/test-support.js:4092:6)
    at http://localhost:4200/assets/test-support.js:4304:12
    at Object.advance (http://localhost:4200/assets/test-support.js:3744:26)
    at begin (http://localhost:4200/assets/test-support.js:5693:20)
    at http://localhost:4200/assets/test-support.js:4691:6

**Comment by k-fish** [comment]
If any of you are having troubles and are on the beta, and don't want to spend the time helping me figure out how to fix your problem, lower your version to the previous major release (2.0.8)

@pablogravielseo if you are using the `3.0.0-beta.1`, there is no longer a differentiation for integration breakpoint tests. Just use `setBreakpoint`. Let me know if that works.

@Fabschu the new syntax for `setBreakpoint` should be `setBreakpoint('large')`, not `setBreakpoint(this, 'large')`. Try it first, and let me know if same error occurs.

**Comment by pablogravielseo** [comment]
@k-fish I downgraded the version to `2.0.8`and now is working, thank you!

**Comment by erichonkanen** [comment]
phew thought I was going crazy, couldn't import the `setBreakpointForIntegrationTest`
